export const FETCH_PORTFOLIO_REQUEST = "FETCH_PORTFOLIO_REQUEST";
export const FETCH_PORTFOLIO_SUCCESS = "FETCH_PORTFOLIO_SUCCESS";
export const FETCH_PORTFOLIO_FAILURE = "FETCH_PORTFOLIO_FAILURE";

export const UPDATE_PORTFOLIO_REQUEST = "FETCH_PORTFOLIO_REQUEST";
export const UPDATE_PORTFOLIO_SUCCESS = "FETCH_PORTFOLIO_SUCCESS";
export const UPDATE_PORTFOLIO_FAILURE = "FETCH_PORTFOLIO_FAILURE";
