export const FETCH_AUTHENTICATION_REQUEST = "FETCH_AUTHENTICATION_REQUEST";
export const FETCH_AUTHENTICATION_SUCCESS = "FETCH_AUTHENTICATION_SUCCESS";
export const FETCH_AUTHENTICATION_FAILURE = "FETCH_AUTHENTICATION_FAILURE";
