name: gh-pages deployment

on:
  push:
    branches:
      - master
      - deployment

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      -
        name: Building React website
        uses: actions/setup-node@v2
        with:
          node-version: '10'

      - run: npm run build
      -
        name: Deploying docs to gh-pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}