name: gh-pages deployment

on:
  push:
    branches:
      - master
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: "10"
      - name: Dependencies fetch
        uses: bahmutov/npm-install@v1.6.0
      - name: Output build
        run: npm run build
